/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import org.tinygroup.placeholder.PlaceholderMainClass;

/**
 *
 * @author acer_
 */
public class login extends javax.swing.JFrame {
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setLocationRelativeTo(null);
        inputIDLogin.setForeground(new Color(153, 153, 153));
        inputPasswordLogin.setForeground(new Color(153, 153, 153));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idLogin = new javax.swing.JLabel();
        inputIDLogin = new javax.swing.JTextField();
        inputPasswordLogin = new javax.swing.JTextField();
        idLogin1 = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Admin");

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setText("LOGIN");

        idLogin.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        idLogin.setText("ID");

        inputIDLogin.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        inputIDLogin.setText("Masukkan ID");
        inputIDLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputIDLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputIDLoginFocusLost(evt);
            }
        });

        inputPasswordLogin.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        inputPasswordLogin.setText("Masukkan Password");
        inputPasswordLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputPasswordLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputPasswordLoginFocusLost(evt);
            }
        });
        inputPasswordLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordLoginActionPerformed(evt);
            }
        });

        idLogin1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        idLogin1.setText("Password");

        buttonLogin.setText("Login");

        buttonExit.setText("Keluar");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLogin)
                            .addComponent(idLogin1))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputIDLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(buttonExit)
                        .addGap(18, 18, 18)
                        .addComponent(buttonLogin)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLogin)
                    .addComponent(inputIDLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLogin1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLogin)
                    .addComponent(buttonExit))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputIDLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputIDLoginFocusGained
        // TODO add your handling code here:
        if(inputIDLogin.getText().equals("Masukkan ID")){
            inputIDLogin.setText("");
            inputIDLogin.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_inputIDLoginFocusGained

    private void inputIDLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputIDLoginFocusLost
        // TODO add your handling code here:
        if(inputIDLogin.getText().equals("")){
            inputIDLogin.setText("Masukkan ID");
            inputIDLogin.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_inputIDLoginFocusLost

    private void inputPasswordLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordLoginActionPerformed

    private void inputPasswordLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputPasswordLoginFocusGained
        // TODO add your handling code here:
        if(inputPasswordLogin.getText().equals("Masukkan Password")){
            inputPasswordLogin.setText("");
            inputPasswordLogin.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_inputPasswordLoginFocusGained

    private void inputPasswordLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputPasswordLoginFocusLost
        // TODO add your handling code here:
        if(inputPasswordLogin.getText().equals("")){
            inputPasswordLogin.setText("Masukkan Password");
            inputPasswordLogin.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_inputPasswordLoginFocusLost

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel idLogin;
    private javax.swing.JLabel idLogin1;
    private javax.swing.JTextField inputIDLogin;
    private javax.swing.JTextField inputPasswordLogin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
